### ISSUE TITLE
missing informations

### ISSUE THREAD

**Issue by marciofoz** [oliveiraped/Reportula#26]
Hello. 
Reportula Admin Dashboard (http://x.x.x.x/public/index.php/admin/dashboard) not show information about the server.   I'm using Centos 7.1.

**Comment by oliveiraped** [comment]
Hi, can you post the php errors please ?

**Comment by marciofoz** [comment]
Good morning.

Attached print screen for check.

I cant see errors in php.log.  I can check in other file ?

Do you speak portuguese ?

Regards.

2015-07-22 18:42 GMT-03:00 Pedro Oliveira notifications@github.com:

**Comment by oliveiraped** [comment]
Sim falo Português, mas no Github prefiro falar em ingles por uma questão de suporte.

I cant see any attatchement .

Without php logs, i cant see wich kind of error you have.

**Comment by marciofoz** [comment]
![reportula](https://cloud.githubusercontent.com/assets/10158758/8850603/cc6425e0-311f-11e5-992c-e345dd0166ec.png)

Here is the file.

Regards.

**Comment by oliveiraped** [comment]
Okay that code is commented, because of the diferent systems, but you can enable just uncomment on this file.

https://github.com/oliveiraped/Reportula/blob/master/app/controllers/admin/DashboardController.php

**Comment by marciofoz** [comment]
Okay, working.
Thank you.
