### ISSUE TITLE
 SQLSTATE[42000]: Syntax error or access violation: 1305

### ISSUE THREAD

**Issue by chevallierIDM** [oliveiraped/Reportula#6]
When i use :  php /var/www/reportula/artisan BaculaStats:collect -vvv

I have : 
![error 4](https://cloud.githubusercontent.com/assets/8101309/3510448/d79f2d96-06a6-11e4-846b-a09e85b87faa.JPG)
 can you help me ?

**Comment by chevallierIDM** [comment]
The function date-part does not exit in MySQL

**Comment by oliveiraped** [comment]
http://stackoverflow.com/questions/20317706/error-datepart-does-not-exist-frp-sql-to-select-last-months-records

If it works please add that to the code .
