### ISSUE TITLE
There is no way to Configure Bacula Client

### ISSUE THREAD

**Issue by newburns** [oliveiraped/Reportula#8]
Fresh CentOS 6.5 instal on the Bacula host.
Installed into the bacula client.
I'm assuming that the bacula client information is loaded through the configurator.
The configurator throws an error

[20:09:37] LOG.error: exception 'InvalidArgumentException' with message 'The "" directory does not exist.' in /var/www/html/reports/vendor/symfony/finder/Symfony/Component/Finder/Finder.php:667
Stack trace:
#0 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(264): Symfony\Component\Finder\Finder->in('')
#1 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Filesystem\Filesystem->allFiles('')
#2 /var/www/html/reports/app/controllers/admin/ConfiguratorController.php(621): Illuminate\Support\Facades\Facade::__callStatic('allFiles', Array)
#3 /var/www/html/reports/app/controllers/admin/ConfiguratorController.php(621): Illuminate\Support\Facades\File::allFiles('')
#4 [internal function]: app\controllers\admin\ConfiguratorController->readbacula()
#5 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('readbacula', Array)
#7 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(app\controllers\admin\ConfiguratorController), Object(Illuminate\Routing\Route), 'readbacula')
#8 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Routing/Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'app\controllers...', 'readbacula')
#9 [internal function]: Illuminate\Routing{closure}()
#10 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Routing/Route.php(104): call_user_func_array(Object(Closure), Array)
#11 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/reports/vendor/barryvdh/laravel-debugbar/src/Barryvdh/Debugbar/Middleware.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Barryvdh\Debugbar\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/reports/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/html/reports/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#22 /var/www/html/reports/public/index.php(49): Illuminate\Foundation\Application->run()
#23 {main}

**Comment by newburns** [comment]
Also...

```
The "" directory does not exist./var/www/html/reports/vendor/symfony/finder/Symfony/Component/Finder/Finder.php#667InvalidArgumentException

} elseif ($glob = glob($dir, GLOB_ONLYDIR)) {
$resolvedDirs = array_merge($resolvedDirs, $glob);
} else {
throw new \InvalidArgumentException(sprintf('The "%s" directory does not exist.', $dir));
}
}
```

**Comment by oliveiraped** [comment]
The configurator is still in very early developing stage, so right now i can not tell you when will okay to use

**Comment by oliveiraped** [comment]
newburns  Check the new Reportula Version, the configurator is ready.
